# Generated by Django 3.1 on 2020-09-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='cropimage',
            field=models.ImageField(blank=True, null=True, upload_to='media/cropimages'),
        ),
    ]
