# Generated by Django 3.1 on 2020-10-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201021_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='article',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='article'),
        ),
        migrations.AddField(
            model_name='article',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='crop',
            field=models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat'), ('rice', 'Rice'), ('tea', 'Tea'), ('coffee', 'Coffee'), ('flowers', 'Flowers'), ('banana', 'Banana'), ('avocando', 'Avocando'), ('cotton', 'Cotton'), ('cabbage', 'Cabbage'), ('sugerCane', 'Sugar Cane'), ('okra', 'Okra'), ('carrot', 'Carrot'), ('cucumber', 'Cucumber'), ('lettuce', 'Lettuce'), ('tomato', 'Tomato'), ('groundnuts', 'Groudnuts'), ('beans', 'Beans'), ('onion', 'Onion'), ('cassava', 'Cassava')], default='maize', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='cropimage',
            field=models.ImageField(blank=True, null=True, upload_to='cropimages/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='stage',
            field=models.CharField(choices=[('general', 'General'), ('land preparation', 'Land Prep'), ('seed selection', 'Seed Selection'), ('crop care', 'Crop Care'), ('harvesting', 'Harvesting'), ('storage', 'Storage'), ('marketing', 'Marketing')], default='general', max_length=100),
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
