# Generated by Django 3.1 on 2020-11-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201031_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.CharField(default='This is a simple excerpt of the blog.', max_length=255),
        ),
    ]
