# Generated by Django 3.1 on 2020-11-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='stage',
            field=models.CharField(choices=[('general', 'General'), ('land preparation', 'Landprep'), ('seed selection', 'Seedselection'), ('crop care', 'Cropcare'), ('harvesting', 'Harvesting'), ('storage', 'Storage'), ('marketing', 'Marketing')], default='general', max_length=100),
        ),
    ]
