# Generated by Django 3.1 on 2020-11-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201101_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='stage',
            field=models.CharField(choices=[('general', 'General'), ('landprep', 'Landprep'), ('seedselection', 'Seedselection'), ('cropcare', 'Cropcare'), ('harvesting', 'Harvesting'), ('storage', 'Storage'), ('marketing', 'Marketing')], default='general', max_length=100),
        ),
    ]
