# Generated by Django 3.1 on 2020-11-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201101_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='crop',
            field=models.CharField(choices=[('maize', 'Maize'), ('wheat', 'Wheat'), ('rice', 'Rice'), ('tea', 'Tea'), ('coffee', 'Coffee'), ('flowers', 'Flowers'), ('banana', 'Banana'), ('avocando', 'Avocando'), ('cotton', 'Cotton'), ('cabbage', 'Cabbage'), ('sugerCane', 'Sugarcane'), ('okra', 'Okra'), ('carrot', 'Carrot'), ('cucumber', 'Cucumber'), ('lettuce', 'Lettuce'), ('tomato', 'Tomato'), ('groundnuts', 'Groudnuts'), ('beans', 'Beans'), ('onion', 'Onion'), ('cassava', 'Cassava')], default='maize', max_length=100),
        ),
    ]
